CREATE TABLE STOCK 
    (
    STOCK_PRODUCTO decimal(18,0) NOT NULL,
    STOCK_SUCURSAL decimal(18,0) NOT NULL,
    STOCK_CANTIDAD decimal(12,2) NOT NULL,
    STOCK_PUNTO_REPOSICION decimal(18,0) NULL,
    STOCK_DETALLE char(100) NULL,
    STOCK_PROXIMA_REPOSICON small NULL,
    )
CREATE TABLE PRODUCTO
    (
    PRODUCTO_CODIGO decimal(18,0) NOT NULL,
    COMPONENTE_CODIGO: [varchar](255),
    ACCESORIO_CODIGO: [decimal](18, 0)
    )
CREATE TABLE SUCURSAL
    (
    SUCURSAL_ID decimal(18, 0) NOT NULL,
    SUCURSAL_DIR nvarchar(255) NULL,
    SUCURSAL_MAIL nvarchar(255) NULL,
    SUCURSAL_TEL decimal(18, 0) NULL,
    ) 

CREATE TABLE CLIENTE
    (
    CLIENTE_ID decimal(18, 0) NOT NULL,
    CLIENTE_APELLIDO nvarchar(255) NULL,
    CLIENTE_NOMBRE nvarchar(255) NULL,
    CLIENTE_DNI decimal(18, 0) NULL,
    CLIENTE_FECHA_NACIMIENTO datetime NULL,
    CLIENTE_MAIL nvarchar(255) NULL,
    CLIENTE_TELEFONO int NULL
    )

CREATE TABLE COMPRA
    (
    COMPRA_ID decimal(18, 0) NOT NULL,
    COMPRA_NUMERO decimal(18, 0) NULL,
    COMPRA_FECHA datetime NULL,
    COMPRA_PRECIO decimal(18, 2) NULL,
    CLIENTE_ID decimal(18, 0) NULL
    )
CREATE COMPRA_ACCESORIO
    (
    SUCURSAL_ID decimal(18, 0) NOT NULL,
    COMPRA_NUMERO decimal(18, 0) NOT NULL,
    ACCESORIO_CODIGO decimal(18, 0) NOT NULL,
    ITEM_PRECIO decimal(18, 2) NULL,
    CANTIDAD decimal(6,0) 
    )
CREATE TABLE ACCESORIO
    (
    ACCESORIO_CODIGO decimal(18, 2) NOT NULL,
    ACCESORIO_DESCRIPCION nvarchar(255) NOT NULL,
    ACCESORIO_PC decimal(18, 2) NOT NULL
    ) 

CREATE TABLE PC
    (
    PC_CODIGO varchar(50) NOT NULL,
    PC_SERIE varchar(50) NULL,
    PC_ALTO decimal(18, 2) NULL,
    PC_ANCHO decimal(18, 2) NULL,
    PC_PROFUNDIDAD decimal(18, 2) NULL,
    PC_PRECIO decimal(18, 2) NULL
    ) 

CREATE TABLE COMPRA_PC
    (
    SUCURSAL_ID decimal(18, 0) NOT NULL,
    COMPRA_NUMERO decimal(18, 0) NOT NULL,
    PC_CODIGO nvarchar(50) NOT NULL,
    ITEM_PRECIO decimal(18, 2) NULL    
    ) 
CREATE TABLE FACTURA
    (
    FACTURA_NUMERO decimal(18, 0) NOT NULL,
    SUCURSAL_ID decimal(18, 0) NULL,
    FACTURA_FECHA datetime NULL,
    FACTURA_PRECIO decimal(18, 2) NULL,
    CLIENTE_ID decimal(18, 0) NULL
    ) 

CREATE TABLE ITEM_FACTURA_ACCESORIO
    (
    ITEM_ACCESORIO decimal(18, 0) NOT NULL,
    FACTURA_NUMERO nvarchar(255)NOT NULL,
    SUCURSAL_ID decimal(18, 0)NOT NULL,
    ITEM_CANTIDAD int NULL,
    ITEM_PRECIO decimal(18, 2) NULL
    ) 


CREATE TABLE ITEM_FACTURA_PC
    (
    ITEM_ACCESORIO decimal(18, 0) NOT NULL,
    FACTURA_NUMERO nvarchar(255) NOT NULL,
    SUCURSAL_ID decimal(18, 0) NOT NULL,
    ITEM_CANTIDAD int NULL,
    ITEM_PRECIO decimal(18, 2) NULL
    ) 

CREATE TABLE COMPONENTE_PC
    (
    PC_CODIGO varchar(50) NOT NULL,
    COMPONENTE_CODIGO decimal(18, 0) NOT NULL
    )

CREATE TABLE DISCO_RIGIDO
    (
    COMPONENTE_CODIGO varchar(255) NOT NULL,
    DISCO_RIGIDO_TIPO nvarchar(255) NULL,
    DISCO_RIGIDO_CAPACIDAD nvarchar(255) NULL,
    DISCO_RIGIDO_VELOCIDAD nvarchar(255) NULL,
    )
CREATE TABLE MEMORIA_RAM
    (
    COMPONENTE_CODIGO varchar(255) NOT NULL,
    MEMORIA_RAM_TIPO nvarchar(255) NULL,
    MEMORIA_RAM_CAPACIDAD nvarchar(255) NULL,
    MEMORIA_RAM_VELOCIDAD nvarchar(255) NULL,
    )
CREATE TABLE PLACA_VIDEO
    (
    COMPONENTE_CODIGO varchar(255) NOT NULL,
    PLACA_VIDEO_CHIPSET nvarchar(255) NULL,
    PLACA_VIDEO_MODELO nvarchar(255) NULL,
    PLACA_VIDEO_VELOCIDAD nvarchar(255) NULL,
    PLACA_VIDEO_CAPACIDAD nvarchar(255) NULL,
    )
CREATE TABLE MICROPROCESADOR
    (
    COMPONENTE_CODIGO varchar(255) NOT NULL,
    MICROPROCESADOR_CACHE varchar(50) NULL,
    MICROPROCESADOR_CANT_HILOS decimal(18, 0) NULL,
    MICROPROCESADOR_VELOCIDAD varchar(50) NULL
    )
CREATE TABLE FABRICANTE
    (
    FABRICANTE_CODIGO decimal(18, 0) NOT NULL,
    FABRICANTE_NOMBRE varchar(50) NULL
    )
CREATE TABLE COMPONENTE
    (
    COMPONENTE_CODIGO varchar(255) NOT NULL,
    COMPONENTE_DESCRIPCION varchar(255) NULL,
    FABRICANTE_CODIGO decimal(18, 0) NULL,
    COMPONENTE_PRECIO decimal(18, 2) NULL
    )
